CREATE TABLE combinedHospitalInfo(
HOSPITAL TEXT,
OSHPDID TEXT,
LONGITUDE TEXT,
LATITUDE TEXT
);

INSERT INTO combinedHospitalInfo 
SELECT HOSPITAL, OSHPDID, LONGITUDE, LATITUDE
FROM combined_2010_to_2023_hospital_data;

ALTER TABLE combined_2010_to_2023_hospital_data DROP COLUMN HOSPITAL;
ALTER TABLE combined_2010_to_2023_hospital_data DROP COLUMN LONGITUDE;
ALTER TABLE combined_2010_to_2023_hospital_data DROP COLUMN LATITUDE;
